### PR TITLE
only try to fetch institutions list and "self" once

### LINKED ISSUE #77: Fetching "self" hammers the browser if fetching it fails
If fetching self fails due to the lookupproxy being down, the frontend locks up the browser by sitting in a loop repeatedly fetching {lookupproxy}/prople/token/self. If fetching the self resource fails, the user should be logged out or an error presented.

### PR DESCRIPTION
**Pull request by rjw57**
> **Testing notes:** in order to show the problem this PR addresses, one needs to arrange for the lookupproxy to fail. This can be done by downloading a little test script, [corsdevserver.py](https://gist.github.com/rjw57/4a1037d71d9fe42673ed0b2d6c68b929) which can replace the lookupproxy. Run via: ``docker-compose stop lookupproxy && python2 corsdevserver.py``. Without this PR applied, the browser should get stuck in a reload loop for the user's profile.

As noted in #77, if fetching the user's profile fails, we get stuck in a loop where the browser tries again and again, hammering the browser.

For both the user's profile and the list of instututions, record a "requestedAt" date which records when the last request was in flight. We then only try to load the corresponding resource if:

1. There is not a resource loaded, and
2. There is not a request in flight, *and*
3. There had not been a request previously.

Number 3 was lacking from our logic before meaning that there was no "memory" of having tried to request the user's profile or list of institutions.

Closes #77

### CODE REVIEW

File: src/redux/reducers/lookupApi.js [hunk 1]
```diff
@@ -59,17 +59,20 @@ export default (state = initialState, action) => {
 
     case PEOPLE_GET_SELF_REQUEST:
       // use an empty object is indicate loading
-      return { ...state, selfLoading: true };
+      return { ...state, selfLoading: true, selfRequestedAt: new Date() };
```
Comment (msb) [inline src/redux/reducers/lookupApi.js]: selfRequestedAt hasn't been defined in state
